### ISSUE TITLE
As a user of the bbl-up task I would like to provide GCP credentials as a task param instead of as a path to a file

### ISSUE THREAD

**Issue by mmb** [cloudfoundry/cf-deployment-concourse-tasks#11]
If the task only accepts a file, that leads me to check it into GitHub or put it in an S3 bucket. I would prefer to provide the credentials in the pipeline directly (like the AWS credentials) so I can store them in a more secure way with my other pipeline secrets.

**Comment by dsabeti** [comment]
Hey @mmb. This would actually require a change to `bbl` -- it currently expects that your credentials are stored in a file. @evanfarrar, do you have any thoughts on this? Would it make sense for `bbl` to allow a string input instead of a file input for GCP credentials?

**Comment by mmb** [comment]
Could the task write the credentials to a file before passing it to bbl?

Our workaround for this is to have a Concourse task that writes a param to a file.

**Comment by evanfarrar** [comment]
We had discussed this awkwardness on the Infrastructure team when we recently started using the cf-deployment-concourse tasks ourselves. We will change the flag to take the contents of the credential file (while preserving file path for backwards compatibility).

**Comment by evanfarrar** [comment]
Tracking this in
https://www.pivotaltracker.com/story/show/142097551

**Comment by dsabeti** [comment]
Hey @mmb. Since we've upgrade to `bbl` 3.0.4, this should probably work. Want to give it a try and report back?

**Comment by mmb** [comment]
This works now. Thanks @dsabeti and @evanfarrar.
