### ISSUE TITLE
bosh-deploy-with-created-release task should default to `name` if `final_name` is unavailable

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/cf-deployment-concourse-tasks#111]
It doesn't look like releases can be named with `final_name` or `name` (but not both) in bosh release. See these two commits on the bosh-cli:

- https://github.com/cloudfoundry/bosh-cli/commit/6668d194e1f57ea827733b4217d40de2eda4fbff
- https://github.com/cloudfoundry/bosh-cli/commit/112f7a214b316df94aa9b8215b079e2d77be24ce

It would be great if this task could support either convention in bosh releases:

Relevant code
https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/b9c1ad424516df9efa84e5fa4353f80facfd4a13/bosh-deploy-with-created-release/task#L38

**Comment by davewalter** [comment]
Hi @MasslessParticle,

Thanks for reporting this. We're surprised that it has taken 4 years for someone to run into this issue! We've implemented a fix [here](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/commit/9e45d4c837a77b956e4e97e99ea44ad0ccd3b322). Could you please try it out and let us know if it works for you?

Thanks,
Dave and @ericpromislow

**Comment by mdelillo** [comment]
@davewalter @ericpromislow This change requires [`yq`](https://pypi.org/project/yq/) which isn't in the dockerfile

**Comment by davewalter** [comment]
Thanks for catching this @mdelillo. I think this has been added so you should be good to go.

**Comment by jamespollard8** [comment]
Closing as fixed by 9e45d4c
