### ISSUE TITLE
bbl 8.4.40 is unable to fetch terraform openstack provider

### ISSUE THREAD

**Issue by hfrenzel** [cloudfoundry/cf-deployment-concourse-tasks#119]
bbl 8.4.40 (from cf-deployment-concourse-tasks commit: 62ad0d48fa3411e6156e0de1140a781bc663c254) is unable to fetch the terraform openstack provider:

```
Initializing provider plugins...

- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "openstack": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

Terraform manager init: Executor init: Run terraform init --upgrade: exit status 1
```

This might be related to https://github.com/cloudfoundry/bosh-bootloader/issues/520.

**Comment by davewalter** [comment]
Hi @hfrenzel,

There was a problem with upgrading to v8.4.41 (and v8.4.42) so I reverted to v8.4.40 until a fix was available. I bumped to [v8.4.43](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v8.4.43) yesterday that includes a bump to terraform v0.11.15 to address this issue in a backwards-compatible way. I am going to go ahead and close this issue, but please feel free to reopen it if the bump to v8.4.443 does not solve your problem.

Thanks,
Dave
