### ISSUE TITLE
FEATURE: bosh-cleanup task optionally uses --all

### ISSUE THREAD

**Issue by chinangela** [cloudfoundry/cf-deployment-concourse-tasks#14]
The `bosh-cleanup` task currently uses `--all` flag. We would like it if the `--all` flag was optional.

Our use case is a couple jobs in our pipeline that deploy two different deployments (it tests upgrading from one to the other).  It would be nice if we could run bosh cleanup without the `--all` option so that the releases for the not-currently-deployed deployment would not get deleted.

Thanks,
Angela & @mcwumbly

**Comment by dsabeti** [comment]
Hey @chinangela, this sounds reasonable. Have you verified that removing `--all` keeps the correct release versions on your BOSH director?

**Comment by chinangela** [comment]
@dsabeti yes, just verified that removing `--all` keeps the versions we want. In general, it seems to keep the latest 3 releases.

**Comment by dsabeti** [comment]
Sounds good. I'll prioritize the story.

**Comment by dsabeti** [comment]
@chinangela, take a look at the task now. It supports use of a `CLEAN_ALL` parameter that you can set to false.

**Comment by chinangela** [comment]
Awesome, thanks a lot!
