### ISSUE TITLE
null bug in delete-deployment task

### ISSUE THREAD

**Issue by bruce-ricard** [cloudfoundry/cf-deployment-concourse-tasks#145]
When attempting to run the [delete-deployment task](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/tree/main/bosh-delete-deployment) with [DELETE_ALL_DEPLOYMENTS](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/503668f646f604e8d6d5c6811d8b7ff46e03e659/bosh-delete-deployment/task.yml#L30) set to `true`, and if your environment doesn't have any deployments, you run into a `null` error:

```
++ jq -r '.Tables[].Rows[].name'
jq: error (at <stdin>:7): Cannot iterate over null (null)
```

Which appears to be coming from this [line of code](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/503668f646f604e8d6d5c6811d8b7ff46e03e659/bosh-delete-deployment/task#L9).

I don't know if this ever worked, or if a recent change to the `bosh` CLI made it break recently.

Here is a fuller log of our task output:

```
+ '[' true = true ']'
+ bosh_delete_all_deployments
+ local deployments
++ bosh deployments --json
++ jq -r '.Tables[].Rows[].name'
jq: error (at <stdin>:7): Cannot iterate over null (null)
+ deployments=
```

**Comment by ctlong** [comment]
@bruce-ricard I've not been able to reproduce this locally, and we haven't seen this error thus far in any of our pipelines.

The next time this occurs, could you please hijack the container and comment here the (sanitized) output of `bosh deployments --json` 🙏 .

**Comment by ctlong** [comment]
I'm going to close this issue due to lack of activity. Please feel free to re-open if something changes.
