### ISSUE TITLE
Feature request: Support bbl's global debug flag

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/cf-deployment-concourse-tasks#3]
We found ourselves in a position where `bbl create-lbs` was failing with no helpful output. We believed this was the `terraform apply` failing, and since that output is scrubbed for security reasons, we didn't know why it was failing. The problem was only visible when we manually ran the command from our own machine and turned out to be a simple resource conflict.

**Comment by dsabeti** [comment]
@aashah This sounds reasonable, but there's one important thing to consider. Terraform will spit out all sorts of sensitive information if you use the `--debug` flag (maybe @evanfarrar can chime in about this).

What the task _could do_ is run `--debug` and then pipe that output to a file. If your task fails, you can `fly hijack` and get the debug output.

**Comment by aashah** [comment]
Looks like this was accepted in the created story. I'm gonna close this if that's cool.

**Comment by dsabeti** [comment]
Thanks @aashah. I thought gitbot would cover this, but apparently it doesn't.
