### ISSUE TITLE
director created by the tasks is open to the world

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/cf-deployment-concourse-tasks#33]
we are running bbl-up task to create our ENVs, we discovered that the director is accessible from everywhere. We would like to restrict this to a whitelisted set of IPs, is that a parameter that can be added to this task?

**Comment by dsabeti** [comment]
Hey @tinygrasshopper. We don't currently have any support for that. However, I'm pretty sure that you'll get something close to what you want once we upgrade to [`bbl` 5.0](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v5.0.0). With that update, all bosh directors created by `bbl` will be deployed to a private IP, with jumpbox that operators can use to access their director.

Would that satisfy your security needs, or do you have a specific reason to want a set of whitelisted IPs?

**Comment by dsabeti** [comment]
Closed due to inactivity, but feel free to reopen.
