### ISSUE TITLE
bosh-deploy-with-created-release task fails if submodule history has changed

### ISSUE THREAD

**Issue by ablease** [cloudfoundry/cf-deployment-concourse-tasks#36]
We have found that rebasing our submodule branch causes the bosh-deploy-with-created-release task to fail.

It appears that the [pull](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/master/bosh-deploy-with-created-release/task#L22) triggers a merge conflict because of the rebase which causes the failure:
```
+ git pull
remote: Counting objects: 189, done.        
remote: Compressing objects: 100% (45/45), done.        
remote: Total 189 (delta 155), reused 178 (delta 144), pack-reused 0        
Receiving objects: 100% (189/189), 20.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (155/155), completed with 14 local objects.
From https://github.com/cloudfoundry-incubator/cloud_controller_ng_sapi
 + 38b8577...17b9ca2 service-instance-sharing -> origin/service-instance-sharing  (forced update)
 + 3e66cdc...bb1b6b3 pr-service-instance-share-summary -> origin/pr-service-instance-share-summary  (forced update)
 + 14ad5a2...fa669e0 pr-service-instance-sharing-bind -> origin/pr-service-instance-sharing-bind  (forced update)
 * [new branch]      tmp-rebase -> origin/tmp-rebase

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

Can we do a fetch and reset instead?

Thanks,
Alex & @Samze

**Comment by dsabeti** [comment]
Hi @ablease. Do you think this would be solved by implementing this feature: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/issues/37? In that case, the concourse task wouldn't need to do `git pull`, because Concourse would be tracking that branch -- although, I'm not sure how the git-resource in Concourse handles rebased branches.

**Comment by dsabeti** [comment]
I'm going to close this issue now that we've merged @kirederik's PR.
