### ISSUE TITLE
bbl-up task should rename "IS_BOSH_LITE" flag

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/cf-deployment-concourse-tasks#44]
The bosh team is using this task in one of our pipelines and found that we could prevent load balancer creation by setting `IS_BOSH_LITE` to true.  This is very useful for us, so we'd like to keep using it.  However, the `IS_BOSH_LITE` name suggests more than just skipping load-balancer creation, so we are a bit worried about relying on this functionality.  Can you please provide a dedicated way to skip load-balancer creation instead?  Thank you!

**Comment by dsabeti** [comment]
Hi @jaresty. The upcoming release of cf-deployment-concourse-tasks will support a `SKIP_LB_CREATION` that -- as its name implies -- skips load balancer creation, independent of the bosh-lite workflow.
