### ISSUE TITLE
run-errand task should allow for keep-alive flag option

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/cf-deployment-concourse-tasks#64]
It would be great to have a param `KEEP_ALIVE` that takes a boolean and adds the `--keep-alive` flag to the `bosh run-errand` command.

**Comment by heyjcollins** [comment]
Hey @wfernandes -- This sounds like it could be a valuable feature for operators. We'll create a story and add it to our backlog. Thanks for the request!

**Comment by davewalter** [comment]
We now have this option available: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/afd9d23fa2a4bfd360a81a78187cb1d98d36d15e/run-errand/task#L24-L26
