### ISSUE TITLE
bosh-deploy task should take in a deployment name as an optional param

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/cf-deployment-concourse-tasks#67]
Currently the bosh-deploy task gets the `deployment_name` by interpolating it from the manifest.

So for deployments such as [kubo-deployment](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/7b00b1464f1ccaa76d498711e53527ee8c2a68a6/manifests/cfcr.yml), we are unable to deploy multiple CFCR clusters using the same director.

It would be super helpful if we could override the manifest's `deployment_name` with a `DEPLOYMENT_NAME` param, just like the `run-errand` task.

**Comment by wfernandes** [comment]
I guess we could use an ops-file to update the name of the deployment. But I still think the param would be simpler.

**Comment by heyjcollins** [comment]
@wfernandes and @ishustava - in cf-deployment 3.0 (to be published any day), the rename-deployment.yml has been merged with the rename-netork.yml - just a heads up that the file referenced in Iryna's comment has been deleted in the next release.

**Comment by heyjcollins** [comment]
Since there's been no response on this issue since July I'm going to close it. If you'd like to see it re-opened, please comment on the issue and reopen.
