### ISSUE TITLE
Support --skip-drain in bosh-delete-deployment

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/cf-deployment-concourse-tasks#68]
It would be nice, in situations where you don't care about draining, to be able to supply a `SKIP_DRAIN` flag to the `bosh-delete-deployment` task.

**Comment by jasonkeene** [comment]
I just realized `delete-deployment` is currently not a flag on the v2 bosh cli. I filed an issue for this in the CLI repo: https://github.com/cloudfoundry/bosh-cli/issues/456

**Comment by jasonkeene** [comment]
Since there is no `--skip-drain` on `delete-deployment` exposing `--force` would do the trick.

**Comment by rosenhouse** [comment]
Is this done? @heyjcollins

**Comment by heyjcollins** [comment]
Hey @rosenhouse -
Apologies I went dark on responding here.
If you set `IGNORE_ERRORS = true`, the task will execute the `bosh delete-deployment` command with the `--force` flag included. I believe this achieves the goal.

I'm going to close this out with my comment, but if there's more to this issue resolution please comment and reopen.
