### ISSUE TITLE
Delete Deployment / Destroy Director flag for no fail

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/cf-deployment-concourse-tasks#83]
Would y'all be open to a PR that allowed the user to specify a "no-fail" type of scenario? We sometimes have situations where deletes have already been triggered and they end up getting triggered again (thus resulting in a pipeline failure). 

I'd love to make it so we do a quick check of if the bbl-state exists and if it does not (and no fail is set) we skip the destroy / delete but return success.

Does this sound ok?

**Comment by heyjcollins** [comment]
As per the thread. we're happy to accept a PR for this so i'm going to go ahead and close this and we'll pull in the PR once y'all have submitted it.

thanks!
